# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Nightgum"
license = "MIT"
licenselink = "https://github.com/mixcas/nightgum/blob/master/LICENSE.md"
description = "A minimal chill vibes dark theme."
homepage = "http://carlossolar.es/"
tags = ["minimal", "dark"]
min_version = 0.13

[author]
  name = "Carlos Solares"
  homepage = "http://carlossolar.es/"
